import type { Metadata } from "next";
// import { Nunito } from "@next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
// import Footer from "./components/footer";

// const nunito = Nunito({
//   weight: ["200", "700"],
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Business Card",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
      {/* <Footer /> */}
    </html>
  );
}
