import AuthButton from "./components/AuthButton";
import CardForm from "./components/cardForm";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Business Card",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="main">
      <h1 className="title">Business Card</h1>

      <div className="container">
        <CardForm />
      </div>
      <AuthButton />
    </main>
  );
}
