// import CardDisplay from "./components/cardDisplay";
import AuthButton from "./components/AuthButton";
import CardForm from "./components/cardForm";
import type { Metadata } from "next";
import UserList from "./components/UserList";

export const metadata: Metadata = {
  title: "Business Card",
  description: "Generated by create next app",
};
// interface CardProps {
//   name: string;
//   email: string;
//   number: number;
// }

export default function Home() {
  return (
    <main
      className="main"
      // className="flex flex-col gap-8 row-start-2 items-center sm:items-start"
    >
      <h1 className="title">Business Card</h1>

      <div className="container">
        <CardForm />
      </div>
      <AuthButton />
      <UserList />
    </main>
  );
}
